const products = [
  {
    name: 'Earring1',
    price: 100,
    description: `Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere impedit quidem delectus quam quisquam voluptates facilis ipsam eveniet, nam vel ut ipsa molestias voluptatem accusantium labore corrupti quos possimus aspernatur!`,
    img: 'https://jaroti-be87.kxcdn.com/jaroti/wp-content/uploads/2022/04/12-404x404.jpg',
    sale: 0,
    hot: true,
    stock: 10,
  },
  {
    name: 'Earring1',
    price: 100,
    description: `Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere impedit quidem delectus quam quisquam voluptates facilis ipsam eveniet, nam vel ut ipsa molestias voluptatem accusantium labore corrupti quos possimus aspernatur!`,
    img: 'https://jaroti-be87.kxcdn.com/jaroti/wp-content/uploads/2022/03/02-404x404.jpg',
    sale: 0,
    hot: true,
    stock: 10,
  },
  {
    name: 'Earring1',
    price: 100,
    description: `Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere impedit quidem delectus quam quisquam voluptates facilis ipsam eveniet, nam vel ut ipsa molestias voluptatem accusantium labore corrupti quos possimus aspernatur!`,
    img: 'https://jaroti-be87.kxcdn.com/jaroti/wp-content/uploads/2022/03/07-404x404.jpg',
    sale: 0,
    hot: true,
    stock: 10,
  },
  {
    name: 'Earring1',
    price: 100,
    description: `Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere impedit quidem delectus quam quisquam voluptates facilis ipsam eveniet, nam vel ut ipsa molestias voluptatem accusantium labore corrupti quos possimus aspernatur!`,
    img: 'https://jaroti-be87.kxcdn.com/jaroti/wp-content/uploads/2022/03/09-404x404.jpg',
    sale: 0,
    hot: true,
    stock: 10,
  },
  {
    name: 'Earring1',
    price: 100,
    description: `Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere impedit quidem delectus quam quisquam voluptates facilis ipsam eveniet, nam vel ut ipsa molestias voluptatem accusantium labore corrupti quos possimus aspernatur!`,
    img: 'https://jaroti-be87.kxcdn.com/jaroti/wp-content/uploads/2022/03/11-404x404.jpg',
    sale: 0,
    hot: true,
    stock: 10,
  },
  {
    name: 'Earring1',
    price: 100,
    description: `Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere impedit quidem delectus quam quisquam voluptates facilis ipsam eveniet, nam vel ut ipsa molestias voluptatem accusantium labore corrupti quos possimus aspernatur!`,
    img: 'https://jaroti-be87.kxcdn.com/jaroti/wp-content/uploads/2022/03/13-404x404.jpg',
    sale: 0,
    hot: true,
    stock: 10,
  },
  {
    name: 'Earring1',
    price: 100,
    description: `Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere impedit quidem delectus quam quisquam voluptates facilis ipsam eveniet, nam vel ut ipsa molestias voluptatem accusantium labore corrupti quos possimus aspernatur!`,
    img: 'https://jaroti-be87.kxcdn.com/jaroti/wp-content/uploads/2022/03/06-404x404.jpg',
    sale: 0,
    hot: true,
    stock: 10,
  },
  {
    name: 'Earring1',
    price: 100,
    description: `Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere impedit quidem delectus quam quisquam voluptates facilis ipsam eveniet, nam vel ut ipsa molestias voluptatem accusantium labore corrupti quos possimus aspernatur!`,
    img: 'https://jaroti-be87.kxcdn.com/jaroti/wp-content/uploads/2022/04/12-404x404.jpg',
    sale: 0,
    hot: true,
    stock: 10,
  },
  {
    name: 'Earring1',
    price: 100,
    description: `Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere impedit quidem delectus quam quisquam voluptates facilis ipsam eveniet, nam vel ut ipsa molestias voluptatem accusantium labore corrupti quos possimus aspernatur!`,
    img: 'https://jaroti-be87.kxcdn.com/jaroti/wp-content/uploads/2022/04/12-404x404.jpg',
    sale: 0,
    hot: true,
    stock: 10,
  },
  {
    name: 'Earring1',
    price: 100,
    description: `Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere impedit quidem delectus quam quisquam voluptates facilis ipsam eveniet, nam vel ut ipsa molestias voluptatem accusantium labore corrupti quos possimus aspernatur!`,
    img: 'https://jaroti-be87.kxcdn.com/jaroti/wp-content/uploads/2022/04/12-404x404.jpg',
    sale: 0,
    hot: true,
    stock: 10,
  },
];
